apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digiocean
spec:
  acme:
    email: vishal@computer4u.com
    preferredChain: ""
    privateKeySecretRef:
      name: digiocean
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx